@extends('layouts.app')

@section('title', 'Marketing PIN Details - Admin')

@section('content')
<div class="mx-auto max-w-3xl space-y-6">
    {{-- Page Header --}}
    <div>
        <a href="{{ route('admin.marketing-pins.index') }}" class="inline-flex items-center text-sm text-gray-500 hover:text-gray-700 mb-4">
            <svg class="mr-1 h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
            </svg>
            Back to Marketing PINs
        </a>
        <h1 class="text-xl font-bold text-gray-900 lg:text-2xl">Marketing PIN Details</h1>
        <p class="mt-1 text-sm text-gray-600">View detailed information about this marketing PIN</p>
    </div>

    {{-- PIN Code Display --}}
    <div class="bg-white rounded-lg shadow p-6">
        <div class="text-center">
            <p class="text-sm font-medium text-gray-500 mb-2">PIN Code</p>
            <div class="flex items-center justify-center gap-4">
                <p class="text-4xl font-mono font-bold text-gray-900" id="pinCode">{{ $marketingPin->code }}</p>
                <button 
                    type="button"
                    onclick="copyToClipboard()"
                    class="inline-flex items-center rounded-md bg-gray-100 px-3 py-2 text-sm font-semibold text-gray-900 hover:bg-gray-200"
                    title="Copy to clipboard"
                >
                    <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/>
                    </svg>
                    <span class="ml-1">Copy</span>
                </button>
            </div>
            <div class="mt-4">
                @if($marketingPin->status === 'active')
                    <span class="inline-flex items-center rounded-full bg-green-100 px-4 py-2 text-sm font-semibold text-green-800">
                        <svg class="mr-2 h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/>
                        </svg>
                        Active
                    </span>
                @elseif($marketingPin->status === 'used')
                    <span class="inline-flex items-center rounded-full bg-blue-100 px-4 py-2 text-sm font-semibold text-blue-800">
                        <svg class="mr-2 h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
                        </svg>
                        Used
                    </span>
                @else
                    <span class="inline-flex items-center rounded-full bg-gray-100 px-4 py-2 text-sm font-semibold text-gray-800">
                        <svg class="mr-2 h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"/>
                        </svg>
                        Expired
                    </span>
                @endif
            </div>
        </div>
    </div>

    {{-- PIN Information --}}
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-lg font-semibold text-gray-900 mb-4">PIN Information</h2>
        <dl class="space-y-4">
            <div class="flex justify-between items-start">
                <dt class="text-sm font-medium text-gray-500">Generated By</dt>
                <dd class="text-sm text-gray-900 text-right">
                    <p class="font-medium">{{ $marketingPin->admin->name }}</p>
                    <p class="text-xs text-gray-500">{{ $marketingPin->admin->email }}</p>
                </dd>
            </div>

            <div class="flex justify-between items-start border-t border-gray-100 pt-4">
                <dt class="text-sm font-medium text-gray-500">Designated Member</dt>
                <dd class="text-sm text-gray-900 text-right">
                    @if($marketingPin->designatedMember)
                        <p class="font-medium">{{ $marketingPin->designatedMember->name }}</p>
                        <p class="text-xs text-gray-500">{{ $marketingPin->designatedMember->email }}</p>
                    @else
                        <span class="text-gray-400">None</span>
                    @endif
                </dd>
            </div>

            <div class="flex justify-between items-start border-t border-gray-100 pt-4">
                <dt class="text-sm font-medium text-gray-500">Created At</dt>
                <dd class="text-sm text-gray-900">
                    {{ $marketingPin->created_at->format('d M Y, H:i') }}
                </dd>
            </div>

            <div class="flex justify-between items-start border-t border-gray-100 pt-4">
                <dt class="text-sm font-medium text-gray-500">Expiration Date</dt>
                <dd class="text-sm text-gray-900">
                    @if($marketingPin->expired_at)
                        <span class="{{ $marketingPin->expired_at->isPast() ? 'text-red-600 font-semibold' : '' }}">
                            {{ $marketingPin->expired_at->format('d M Y, H:i') }}
                        </span>
                        @if($marketingPin->expired_at->isPast())
                            <span class="ml-2 text-xs text-red-600">(Expired)</span>
                        @endif
                    @else
                        <span class="text-gray-400">No expiration</span>
                    @endif
                </dd>
            </div>
        </dl>
    </div>

    {{-- Usage Information (only if used) --}}
    @if($marketingPin->status === 'used' && $marketingPin->redeemedByMember)
        <div class="bg-white rounded-lg shadow p-6">
            <h2 class="text-lg font-semibold text-gray-900 mb-4">Usage Information</h2>
            <dl class="space-y-4">
                <div class="flex justify-between items-start">
                    <dt class="text-sm font-medium text-gray-500">Used By</dt>
                    <dd class="text-sm text-gray-900 text-right">
                        <p class="font-medium">{{ $marketingPin->redeemedByMember->name }}</p>
                        <p class="text-xs text-gray-500">{{ $marketingPin->redeemedByMember->email }}</p>
                    </dd>
                </div>

                <div class="flex justify-between items-start border-t border-gray-100 pt-4">
                    <dt class="text-sm font-medium text-gray-500">Used At</dt>
                    <dd class="text-sm text-gray-900">
                        {{ $marketingPin->used_at?->format('d M Y, H:i') }}
                    </dd>
                </div>

                <div class="flex justify-between items-start border-t border-gray-100 pt-4">
                    <dt class="text-sm font-medium text-gray-500">Member Profile</dt>
                    <dd class="text-sm">
                        <a href="{{ route('admin.members') }}" class="text-blue-600 hover:text-blue-900">
                            View member details
                        </a>
                    </dd>
                </div>
            </dl>
        </div>
    @endif
</div>

@push('scripts')
<script>
function copyToClipboard() {
    const pinCode = document.getElementById('pinCode').textContent;
    
    // Use the modern Clipboard API
    if (navigator.clipboard && window.isSecureContext) {
        navigator.clipboard.writeText(pinCode).then(() => {
            // Show success feedback
            showCopyFeedback('Copied!');
        }).catch(err => {
            console.error('Failed to copy:', err);
            fallbackCopyToClipboard(pinCode);
        });
    } else {
        // Fallback for older browsers
        fallbackCopyToClipboard(pinCode);
    }
}

function fallbackCopyToClipboard(text) {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    document.body.appendChild(textArea);
    textArea.select();
    
    try {
        document.execCommand('copy');
        showCopyFeedback('Copied!');
    } catch (err) {
        console.error('Fallback: Failed to copy', err);
        showCopyFeedback('Failed to copy');
    }
    
    document.body.removeChild(textArea);
}

function showCopyFeedback(message) {
    // Create a temporary toast notification
    const toast = document.createElement('div');
    toast.textContent = message;
    toast.className = 'fixed top-4 right-4 bg-green-600 text-white px-4 py-2 rounded-md shadow-lg z-50 transition-opacity duration-300';
    document.body.appendChild(toast);
    
    // Remove toast after 2 seconds
    setTimeout(() => {
        toast.style.opacity = '0';
        setTimeout(() => {
            document.body.removeChild(toast);
        }, 300);
    }, 2000);
}
</script>
@endpush
@endsection
